### ISSUE TITLE
can't use ggml-gpt4all-j-v1.3-groovy.bin

### ISSUE THREAD

**Issue by nilvaes** [marella/chatdocs#18]
I wanted to use another llm but i had some errors as:

![Screenshot 2023-06-14 173048](https://github.com/marella/chatdocs/assets/90209312/421c8a8b-7141-468a-adfd-1ce9034bf4db)

and this is my chatdocs.yml:

![Screenshot 2023-06-14 173357](https://github.com/marella/chatdocs/assets/90209312/c05a716a-f9df-44b9-ab79-c2b94fd4b886)

I already did `pip install ctransformers` and `set CT_CUBLAS=1 pip install ctransformers --no-binary ctransformers`

How can i use ggml-gpt4all-j-v1.3-groovy.bin?
I'm sorry if these questions/problems are easy. I'm still a beginner on this subject but i really love the work you're putting on.

**Comment by marella** [comment]
> I'm sorry if these questions/problems are easy. I'm still a beginner on this subject but i really love the work you're putting on.

Hey, no worries. Actually this is not an easy problem to figure out. I think gpt4all team changed their models and are using custom formats for their models instead of the standard ggml format, so it is not working with the ggml library.

Any reason you want to use the gpt4all-j model? I think the default model Wizard-Vicuna-7B-Uncensored is better than gpt4all-j and has similar size. Please note that only llama based models like Wizard-Vicuna support GPU. so gpt4all-j doesn't support GPU. If you want to use a gpt4all model you can try https://huggingface.co/TheBloke/GPT4All-13B-snoozy-GGML/tree/main which is also better than gpt4all-j.

Also any of the GGML models from https://huggingface.co/TheBloke will work.

**Comment by nilvaes** [comment]
My Specs:
cpu: amd ryzen 5 2600x 6Core
gpu: gtx 1660 super 

i wanted to get faster responses. For now with gpu_layers: 30 i'm nearly using my all vrams and also using my cpu and i get a response in 37seconds.

**Comment by marella** [comment]
I don't think gpt4all-j will be faster than the default llama model. On [Open LLM Leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard), gpt4all-13b-snoozy doesn't appear to be good compared to other 13B models like Wizard-Vicuna-13B-Uncensored
Depending on your RAM you may or may not be able to run 13B models. RAM requirements are mentioned in the [model card](https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GGML#provided-files).

Recently some new quantization formats were released which significantly reduce the model size and require less memory.
Try the `...q2_K.bin` files from [Wizard-Vicuna-7B-Uncensored-GGML](https://huggingface.co/TheBloke/Wizard-Vicuna-7B-Uncensored-GGML/tree/main) and [Wizard-Vicuna-13B-Uncensored-GGML](https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GGML/tree/main). They will be faster but will have less quality:

`chatdocs.yml`:

```yml
ctransformers:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-GGML
  model_file: Wizard-Vicuna-7B-Uncensored.ggmlv3.q2_K.bin
  model_type: llama
```

Also try running with `gpu_layers: 0`. Sometimes running on just CPU can be faster if VRAM is not enough.

**Comment by mt-v** [comment]
First of all great work @marella . This library makes it so easy to install and run. 

So, I have similar issue where my 2gb Nvidia Quadro P620 runs out of memory. And I am making a chatbot app for commercial usage, so which model can I use for it? 
(This is just for testing until I buy a cloud for commercial use)

**Comment by nilvaes** [comment]
hi, @mt-v . There is a list of commercial usable LLMs:
 https://github.com/eugeneyan/open-llms

I would recommend you to check and research which models are suitable for your project. If you want faster responds you need a better cpu ram or gpu, if you going to use it locally for now.

If your vram (gpu) runs out of memory, you should play with the `gpu_layers: 50`. I have gtx 1660 SUPER (6gb vram) and ` gpu_layers: 30` was the best solution for me.

I would love to hear your accomplishments throughout your project, keep me notified.

**Comment by marella** [comment]
Thanks @mt-v I hope nilvaes comment answered your questions.

---

@nilvaes if you are still looking for gpt4all-j model, you can use this file: https://huggingface.co/rustformers/gpt4all-j-ggml/blob/main/gpt4all-j-q4_0.bin which is in the standard ggml format.

`chatdocs.yml`:

```yml
ctransformers:
  model: rustformers/gpt4all-j-ggml
  model_file: gpt4all-j-q4_0.bin
  model_type: gptj
```

**Comment by mt-v** [comment]
> 

@nilvaes @marella Thank you very much guys! This is exactly what I was looking for :)

I will keep you posted on the project. Once again, thanks for your response and this wonderful project!

**Comment by mt-v** [comment]
Hey guys! So I have upgraded to RTX 3060 12gb for testing the models. Do we have a support to configure this like an API server as you see in LocalAI. So that you can switch between different models, backends and OpenAI API.

**Comment by marella** [comment]
Hey, it uses WebSockets, so it doesn't have a REST API. See [backend](https://github.com/marella/chatdocs/blob/ff0f962972ba65f0bccbf2e81875a95bae7473b5/chatdocs/ui.py#L39) and [frontend](https://github.com/marella/chatdocs/blob/ff0f962972ba65f0bccbf2e81875a95bae7473b5/chatdocs/data/index.html#L4) code for reference.
Switching models might not be feasible because it will require more memory for each model loaded.
