### ISSUE TITLE
Running chatdocs ui on headless server

### ISSUE THREAD

**Issue by silvernailj** [marella/chatdocs#32]
I'm attempting to run this on a headless server (Ubuntu 22.04) where I have considerably more resources, and can't get internet access to it.  I've attempted to modify the IP/Port numbers on the chatdocs.yml, tried modifying the ui.py, nothing.  Keeps returning the 
* Running on http://localhost:5000 

local firewalls are disabled and the device is reachable via Ping.

Any suggestions?

**Comment by drewzeee** [comment]
I'm here for guidance on this as well

**Comment by marella** [comment]
I just released a new version 0.2.5 which adds `host` and `auth` options.

Add the following to `chatdocs.yml` to allow access via network:

```yml
host: 0.0.0.0
```

To connect, you should use the public IP of your server instead of localhost: http://SERVER_IP:5000

But this is not secure as it allows public access, so you can also add `auth: true` to `chatdocs.yml` which generates a random authenticated URL to access the UI.

For more security, you can limit your server/port access to your local machine's IP e.g. using security groups if you are using AWS.
