### ISSUE TITLE
model_file entry in chatdocs.yml should not include .safetensors at end

### ISSUE THREAD

**Issue by lightnin** [marella/chatdocs#67]
According to the README and the default chatdocs.yml, model file entries appear as following:
model_file: Wizard-Vicuna-7B-Uncensored-GPTQ-4bit-128g.no-act-order.safetensors

This results in a file not found error. Remove the ".safetensors" and thinks start working better.

References:
https://huggingface.co/TheBloke/guanaco-33B-GPTQ/discussions/12#649eec3323c9440af9dd99ff

**Comment by marella** [comment]
The `.safetensors` extension is removed internally. The issue was that the model file in TheBloke's repo was renamed from `Wizard-Vicuna-7B-Uncensored-GPTQ-4bit-128g.no-act-order.safetensors` to `Wizard-Vicuna-7B-Uncensored-GPTQ-4bit-128g.no-act.order.safetensors` which I [updated](https://github.com/marella/chatdocs/commit/29413117a5c2a0821efbc08452f3192e3e949006) now and will release in the next version. So adding the following change to your `chatdocs.yml` file will resolve the issue:

```yml
gptq:
  model_file: Wizard-Vicuna-7B-Uncensored-GPTQ-4bit-128g.no-act.order.safetensors
```
